version: '2'
services:
  nginx:
    image: nginx:1.15.0
    container_name: django_bokeh_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src/server:/src
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/server/app/static:/static
    depends_on:
      - app
  app:
    build: .
    image: rbrecheisen/django_bokeh:latest
    container_name: django_bokeh_app
    command: bash -c "gunicorn server.wsgi -b 0.0.0.0:8001"
    environment:
      - SECRET_KEY
    volumes:
      - ./src/server:/src
    stdin_open: true
    tty: true
